/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.SQLcomm;
import Model.*;
import java.util.ArrayList;
import Control.SQLcomm;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rwatkins
 */
public class ManagerDash extends javax.swing.JFrame {

    /**
     * Creates new form ManagerDash
     */
    public ManagerDash() {
        initComponents();
        con = new SQLcomm();
        fillManagerTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMainDisplay = new javax.swing.JTable();
        lblSearch = new java.awt.Label();
        txtSearch = new java.awt.TextField();
        lblTitleManDash = new java.awt.Label();
        btnEditShipment = new java.awt.Button();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuNewShipment = new javax.swing.JMenuItem();
        mnuNewUser = new javax.swing.JMenuItem();
        mnuRefresh = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        mnuEditShipment = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuEditUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMainDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Shipment ID", "Last Name", "First Name", "Status", "Weight", "Date In", "Date Out"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMainDisplay);

        lblSearch.setText("Search");

        txtSearch.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtSearchTextValueChanged(evt);
            }
        });

        lblTitleManDash.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitleManDash.setText("Management Dashboard");

        btnEditShipment.setLabel("Edit Shipment");
        btnEditShipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditShipmentActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        mnuNewShipment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuNewShipment.setText("New Shipment");
        mnuNewShipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewShipmentActionPerformed(evt);
            }
        });
        jMenu1.add(mnuNewShipment);

        mnuNewUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mnuNewUser.setText("New User");
        jMenu1.add(mnuNewUser);

        mnuRefresh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mnuRefresh.setText("Refresh Database");
        mnuRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRefreshActionPerformed(evt);
            }
        });
        jMenu1.add(mnuRefresh);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        mnuEditShipment.setText("Edit");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Edit Shipment");
        mnuEditShipment.add(jMenuItem1);

        mnuEditUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuEditUser.setText("Edit Users");
        mnuEditShipment.add(mnuEditUser);

        jMenuBar1.add(mnuEditShipment);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitleManDash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(btnEditShipment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitleManDash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditShipment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNewShipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewShipmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuNewShipmentActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRefreshActionPerformed
        fillManagerTable();
    }//GEN-LAST:event_mnuRefreshActionPerformed

    private void btnEditShipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditShipmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditShipmentActionPerformed

    private void txtSearchTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtSearchTextValueChanged
        ArrayList <Shipment> shipmentSearch = con.getShipments(txtSearch.getText());
        fillManagerTable(shipmentSearch);
    }//GEN-LAST:event_txtSearchTextValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnEditShipment;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label lblSearch;
    private java.awt.Label lblTitleManDash;
    private javax.swing.JMenu mnuEditShipment;
    private javax.swing.JMenuItem mnuEditUser;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuNewShipment;
    private javax.swing.JMenuItem mnuNewUser;
    private javax.swing.JMenuItem mnuRefresh;
    private javax.swing.JTable tblMainDisplay;
    private java.awt.TextField txtSearch;
    // End of variables declaration//GEN-END:variables
    private SQLcomm con;


    private void fillManagerTable() {
        ArrayList <Shipment> shipments = con.getShipments();
        DefaultTableModel model = (DefaultTableModel) tblMainDisplay.getModel();
        Object rowData[] = new Object[7];
        model.setRowCount(0);
        for(int i = 0; i<shipments.size(); i++){
            rowData[0] = shipments.get(i).getShipment_id();
            rowData[1] = shipments.get(i).getLast_name();
            rowData[2] = shipments.get(i).getFirst_name();
            rowData[3] = shipments.get(i).getStatus();
            rowData[4] = shipments.get(i).getWeight();
            rowData[5] = shipments.get(i).getDate_in();
            rowData[6] = shipments.get(i).getDate_out();
            model.addRow(rowData);
        }
    }
    
    private void fillManagerTable(ArrayList<Shipment> shipments) {
        DefaultTableModel model = (DefaultTableModel) tblMainDisplay.getModel();
        Object rowData[] = new Object[7];
        model.setRowCount(0);
        for(int i = 0; i<shipments.size(); i++){
            rowData[0] = shipments.get(i).getShipment_id();
            rowData[1] = shipments.get(i).getLast_name();
            rowData[2] = shipments.get(i).getFirst_name();
            rowData[3] = shipments.get(i).getStatus();
            rowData[4] = shipments.get(i).getWeight();
            rowData[5] = shipments.get(i).getDate_in();
            rowData[6] = shipments.get(i).getDate_out();
            model.addRow(rowData);
        }
    }
    

}
